name: Build and Release Polygon

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  BuildAndRelease:
    name: Build and Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: polygon.ahk
          out: polygon-${{ env.TAG_NAME }}.exe
          icon: polygon.png
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: polygon-${{ env.TAG_NAME }}.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  DraftReleaseNotes:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
