name: Build and Release Polygon

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  BuildAndRelease:
    name: Build and Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          fetch-depth: 0
      - name: Build Polygon
        shell: pwsh
        if: startsWith(github.ref, 'refs/tags/v')
        run: .\polygon.ps1;
      - name: Upload to GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            ./build/polygon-x*.zip
            ./build/polygon-x*.msi
            ./build/polygon-checksum.txt
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
